AWSTemplateFormatVersion: "2010-09-09"
Description: "Scheduled ETL Lambda for ps-creel-api (runs every 20 minutes by default)"

Parameters:
  EtlFunctionName:
    Type: String
    Default: "ps-creel-etl"
    Description: "Lambda function name"
  EtlCodeS3Bucket:
    Type: String
    Description: "S3 bucket containing the Lambda deployment package"
  EtlCodeS3Key:
    Type: String
    Description: "S3 key for the Lambda deployment package (zip)"
  EtlHandler:
    Type: String
    Default: "dist/etl/lambda.handler"
    Description: "Handler path in the deployment package"
  EtlRuntime:
    Type: String
    Default: "nodejs20.x"
    AllowedValues:
      - "nodejs18.x"
      - "nodejs20.x"
    Description: "Lambda runtime"
  EtlTimeout:
    Type: Number
    Default: 300
    MinValue: 10
    MaxValue: 900
    Description: "Lambda timeout in seconds"
  EtlMemory:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: "Lambda memory in MB"
  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Description: "CloudWatch log retention in days"
  ScheduleExpression:
    Type: String
    Default: "rate(20 minutes)"
    Description: "EventBridge schedule expression"
  DatabaseUrl:
    Type: String
    NoEcho: true
    Description: "DATABASE_URL for Prisma (required)"
  DirectUrl:
    Type: String
    NoEcho: true
    Default: ""
    Description: "DIRECT_URL for Prisma migrations (optional)"
  CsvUrl:
    Type: String
    Default: "https://wdfw.wa.gov/fishing/reports/creel/puget-annual/export?_format=csv"
    Description: "Override CSV_URL (optional)"
  SampleDateParam:
    Type: String
    Default: ""
    Description: "Optional WDFW sample_date param value"
  BatchSize:
    Type: String
    Default: "50"
    Description: "Batch size for DB writes"
  DryRun:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "If true, ETL will not write to the database"

Resources:
  EtlLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EtlFunctionName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  EtlFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref EtlFunctionName
      Handler: !Ref EtlHandler
      Runtime: !Ref EtlRuntime
      Timeout: !Ref EtlTimeout
      MemorySize: !Ref EtlMemory
      Role: !GetAtt EtlLambdaRole.Arn
      Code:
        S3Bucket: !Ref EtlCodeS3Bucket
        S3Key: !Ref EtlCodeS3Key
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          DIRECT_URL: !Ref DirectUrl
          CSV_URL: !Ref CsvUrl
          SAMPLE_DATE_PARAM: !Ref SampleDateParam
          BATCH_SIZE: !Ref BatchSize
          DRY_RUN: !Ref DryRun

  EtlLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${EtlFunction}"
      RetentionInDays: !Ref LogRetentionInDays

  EtlScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Run ETL on a schedule"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt EtlFunction.Arn
          Id: "EtlLambdaTarget"

  EtlInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref EtlFunction
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EtlScheduleRule.Arn

Outputs:
  EtlFunctionArn:
    Description: "ETL Lambda ARN"
    Value: !GetAtt EtlFunction.Arn
  EtlScheduleRuleArn:
    Description: "EventBridge rule ARN"
    Value: !GetAtt EtlScheduleRule.Arn
